# Site Settings
baseurl: ""
url : "https://asmit-a.github.io"

# Blog Settings
theme_settings :
  title : Asmita Majumder
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Asmita Majumder
    description : UCLA '22, B.S. in Applied Mathematics with a Specialization in Computing and a Minor in Bioinformatics :)
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  asmitaroymajumder@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: asmit-a
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
